version: "2.1"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    group_add:
      - "998" # Change this to match your "render" host group id and remove this comment
    volumes:
      - jellyconf:/config
      - /routet/to:/data
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - radarrconf:/config
      - /routet/to/films:/movies #optional
      - /routet/to/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - sonarrconf:/config
      - /routet/to:/tv #optional
      - /routet/to:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - prowlarrconf:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - USER=user1 #change user
      - PASS=password1 #change password
    volumes:
      - transmissionconf:/config
      - /routet/to/downloads:/downloads
      - /routet/to:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

volumes:
  radarrconf:
    external: true
    name: dock-jelly-arr_radarrconf
  sonarrconf:
    external: true
    name: dock-jelly-arr_sonarrconf
  jellyconf:
  transmissionconf:
    external: true
    name: dock-jelly-arr_transmissionconf
  prowlarrconf:
    external: true
    name: dock-jelly-arr_prowlarrconf